[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  API_BASE_URL = "https://apirolli-movieapi-7215bc5accc0.herokuapp.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
